add signin functionality
moyarsuccess/gathering pull request #13
Opened 2023-03-29 17:33 UTC by idaosk

created a viewmodel & activity for sign in

2023-03-29 17:36 UTC, idaosk commented
Ii created the ViewModel class to the best of my knowledge but I need a tutorial on this subject to learn properly. 
@moyarsuccess @amirziarati

2023-04-07 18:31 UTC, Animansoubi commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-analytics-ktx'
yes, I've already added them.

2023-04-07 18:37 UTC, Animansoubi reviewed
LGTM

2023-04-09 17:43 UTC, moyarsuccess requested changes

2023-04-09 17:43 UTC, moyarsuccess commented on app/src/main/java/com/gathering/android/Application.kt
> +import com.google.firebase.FirebaseApp
This dependency here is extra.

2023-04-09 17:43 UTC, moyarsuccess commented on app/src/main/java/com/gathering/android/Application.kt
> +}
Why you have added these curly braces?

2023-04-09 19:09 UTC, idaosk commented on app/src/main/java/com/gathering/android/Application.kt
> +import com.google.firebase.FirebaseApp
done!

2023-04-09 19:17 UTC, moyarsuccess approved these changes

2023-04-09 20:42 UTC, moyarsuccess approved these changes

2023-04-09 20:42 UTC, merged