[6] Add Hilt dependencies
moyarsuccess/gathering pull request #6
Opened 2023-02-28 18:40 UTC by Animansoubi

Add an Application class
Add an Application module class
Add Hilt dependencies
Add dagger plugin and kept
@idaosk 
@moyar1532

2023-02-28 20:51 UTC, moyarsuccess requested changes

2023-02-28 20:51 UTC, moyarsuccess commented on app/src/main/java/com/gathering/android/Application.kt
> +class Application : Application()
This custom application class needs to be added to the manifest as well.

2023-02-28 20:58 UTC, moyarsuccess approved these changes
Now LGTM

2023-03-01 17:16 UTC, idaosk approved these changes

2023-03-13 23:12 UTC, merged