[T8] Add signUp UI page
moyarsuccess/gathering pull request #8
Opened 2023-03-13 20:10 UTC by Animansoubi

add a logo
add custom button
add custom edit text
add icons

2023-03-13 23:10 UTC, moyarsuccess requested changes

2023-03-13 23:10 UTC, moyarsuccess commented on app/src/main/java/com/gathering/android/MainActivity.kt
> +        findViewById<Button>(R.id.btn_test).setOnClickListener {
You should use view binding here

2023-03-13 23:10 UTC, moyarsuccess commented on app/src/main/java/com/gathering/android/SignUpActivity.kt
> +        setContentView(R.layout.activity_sign_up)
Same as above, use view binding please.

2023-03-13 23:10 UTC, moyarsuccess commented on app/src/main/res/layout/activity_sign_up.xml
> +    <com.google.android.material.textfield.TextInputLayout
Please use styles here to manage the duplicated resources and configurations that was used here.

2023-03-13 23:10 UTC, moyarsuccess commented on app/src/main/res/values/strings.xml
> +    <string name="enter_password_again">Please Enter your password again</string>
Change to Confirm password

2023-03-14 16:06 UTC, idaosk approved these changes

2023-03-14 20:20 UTC, closed without merging